{% set version = "1.2.3" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-harmony
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/harmony_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/harmony/harmony_{{ version }}.tar.gz
  sha256: 9ab815ab0260a6726b2bb48de3fa4c3cad36acbe9ac6158d515fb16ea66bbddd

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'            # [win]
    - '*/Rblas.dll'        # [win]
    - '*/Rlapack.dll'      # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-rcppprogress               # [build_platform != target_platform]
    - r-dplyr                      # [build_platform != target_platform]
    - r-ggplot2                    # [build_platform != target_platform]
    - r-cowplot                    # [build_platform != target_platform]
    - r-rhpcblasctl                # [build_platform != target_platform]
    - r-rcpp                       # [build_platform != target_platform]
    - r-rlang                      # [build_platform != target_platform]
    - r-tibble                     # [build_platform != target_platform]
    - r-matrix                     # [build_platform != target_platform]
    - r-rcpparmadillo              # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib('c') }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib('m2w64_c') }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ compiler('fortran') }}    # [osx and arm64]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-matrix
    - r-rcpp
    - r-rcpparmadillo
    - r-rcppprogress
    - r-rhpcblasctl
    - r-cowplot
    - r-dplyr
    - r-ggplot2
    - r-rlang
    - r-tibble
    - libblas
    - liblapack
  run:
    - r-base
    - r-matrix
    - r-rcpp
    - r-rcpparmadillo
    - r-rcppprogress
    - r-rhpcblasctl
    - r-cowplot
    - r-dplyr
    - r-ggplot2
    - r-rlang
    - r-tibble

test:
  requires:
    - r-testthat
    - r-codetools
  source_files:
    - tests/
  commands:
    - $R -e "library('harmony')"                                                      # [not win]
    - $R -e "testthat::test_file('tests/testthat.R', stop_on_failure=TRUE)"           # [not win]
    - "\"%R%\" -e \"library('harmony')\""                                             # [win]
    - "\"%R%\" -e \"testthat::test_file('tests/testthat.R', stop_on_failure=TRUE)\""  # [win]

about:
  home: https://portals.broadinstitute.org/harmony/
  dev_url: https://github.com/immunogenomics/harmony
  license: GPL-3.0-only
  summary: Implementation of the Harmony algorithm for single cell integration, described in Korsunsky et al <doi:10.1038/s41592-019-0619-0>. Package includes a standalone Harmony function and interfaces to external frameworks.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - dillonroach
